Add files via upload
AnnaNamyatova/Python_HW7 pull request #1
Opened 2018-11-07 20:24 UTC by AnnaNamyatova

2018-11-09 13:54 UTC, Alisa1195 commented on DNA_RNA_classes.py
> +class Dna(str):
Обычно в скобках прописывается класс, от которого идет наследование, не видела, чтобы тип можно было прописывать. Правда, интерпретатор не ругается на это

2018-11-09 13:58 UTC, Alisa1195 commented on DNA_RNA_classes.py
> +        for i in self:
стоит проходить по dna_seq, self это просто начальный аргумент

2018-11-09 14:01 UTC, Alisa1195 commented on DNA_RNA_classes.py
> +        codes = 'AaCcGgTtRrWwSsYyKkVvHhDdBbNn'
А для чего остальные буквы?

2018-11-09 14:02 UTC, Alisa1195 commented on DNA_RNA_classes.py
> +        self = self.upper()
здесь также нужна сама строка dna_seq

2018-11-09 14:04 UTC, Alisa1195 commented on DNA_RNA_classes.py
> +        compl_sequence = self.translate(self.maketrans('ACGTRWSYKMVHDBN', 'TGCAYWSRMKBDHVN'))
мой интерпретатор говорит, что у строки нет метода translate

2018-11-09 14:18 UTC, Alisa1195 requested changes
Комментарии по поводу синтаксиса классов

2018-11-10 13:01 UTC, AnnaNamyatova commented on DNA_RNA_classes.py
> +        codes = 'AaCcGgTtRrWwSsYyKkVvHhDdBbNn'
Это для того, чтобы показать, что не понятно, какой на этом месте нуклеотид. К примеру, G или C - это S, A или T - это W, N - любой нуклеотид, и так далее.

2018-11-10 13:03 UTC, Alisa1195 commented on DNA_RNA_classes.py
> +        codes = 'AaCcGgTtRrWwSsYyKkVvHhDdBbNn'
Ага, я разобралась, спасибо)

2018-11-10 13:03 UTC, Alisa1195 commented on DNA_RNA_classes.py
> +        for i in self:
если проблема была в моем интерпретаторе, то эти комментарии снимаются

2018-11-10 13:33 UTC, AnnaNamyatova commented on DNA_RNA_classes.py
> +class Dna(str):
А у меня почему-то без (str) интерпретатор ругается и говорит, что "TypeError: 'Dna' object is not iterable"

2018-11-10 13:38 UTC, AnnaNamyatova commented on DNA_RNA_classes.py
> +        for i in self:
Сейчас проверила, у меня и так, и так получается. Хорошо.

2018-11-10 13:42 UTC, Alisa1195 commented on DNA_RNA_classes.py
> +class Dna(str):
Просто на этапе создания класса скобки обычно пустые, а уже при создании экземпляра класса в скобки будет прописываться строка

2018-11-10 20:54 UTC, AnnaNamyatova commented on DNA_RNA_classes.py
> +class Dna(str):
Код не работает, если убирать str из class Dna(str)

2018-11-10 21:04 UTC, merged

2018-11-12 07:24 UTC, agbragin commented
@AnnaNamyatova Why did you merged the branch into `master`? We've discussed, that the answer to the task is the submitted review/pull request. Please, reopen the PR with the changes to review.

2018-11-12 09:29 UTC, AnnaNamyatova commented
This was make mistake, I have merged it accidentally. I will do my best to fix it.